import { DEFAULT_PARAMS } from '../params.config';

export interface Preset {
  id: string;
  name: string;
  description: string;
  params: Record<string, any>;
}

export const PRESETS: Preset[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Clean starting point with all defaults',
    params: { ...DEFAULT_PARAMS },
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    description: 'Bold, aggressive, raw design',
    params: {
      ...DEFAULT_PARAMS,
      weight: 120,
      strokeWidth: 8,
      strokeColor: '#000000',
      color1: '#FF3B30',
      color2: '#FF3B30',
      fillMode: 'Solid',
      cornerRadius: 0,
      scaleX: 110,
    },
  },
  {
    id: 'y2k-chrome',
    name: 'Y2K Chrome',
    description: 'Shiny metallic aesthetic from the early 2000s',
    params: {
      ...DEFAULT_PARAMS,
      color1: '#C0C0C0',
      color2: '#FFFFFF',
      fillMode: 'Linear Gradient',
      gradientAngle: 135,
      glowIntensity: 20,
      shadowBlur: 15,
      shadowX: 4,
      shadowY: 4,
    },
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    description: 'Geometric, primary colors, no frills',
    params: {
      ...DEFAULT_PARAMS,
      cornerRadius: 0,
      color1: '#E63946',
      strokeColor: '#000000',
      strokeWidth: 6,
      scaleX: 90,
      weight: 80,
    },
  },
  {
    id: 'organic',
    name: 'Organic',
    description: 'Natural, flowing shapes with soft edges',
    params: {
      ...DEFAULT_PARAMS,
      cornerRadius: 60,
      curveSmoothing: 85,
      color1: '#52B788',
      color2: '#40916C',
      fillMode: 'Linear Gradient',
      waveAmplitude: 8,
    },
  },
  {
    id: 'pixel',
    name: 'Pixel',
    description: 'Digital pixel art aesthetic',
    params: {
      ...DEFAULT_PARAMS,
      cornerRadius: 0,
      weight: 60,
      scaleX: 100,
      color1: '#00FF41',
      color2: '#008F11',
      fillMode: 'Solid',
      strokeColor: '#00FF41',
      strokeWidth: 1,
      backgroundColor: '#0A0A0A',
      backgroundTransparent: false,
    },
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    description: 'Ornate geometric luxury style',
    params: {
      ...DEFAULT_PARAMS,
      scaleX: 75,
      weight: 30,
      color1: '#C9A84C',
      color2: '#8B6914',
      fillMode: 'Linear Gradient',
      gradientAngle: 90,
      frameShape: 'Shield',
      framePadding: 20,
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Electric glow on dark background',
    params: {
      ...DEFAULT_PARAMS,
      color1: '#FF00FF',
      color2: '#00FFFF',
      fillMode: 'None',
      strokeColor: '#FF00FF',
      strokeWidth: 3,
      glowIntensity: 40,
      backgroundColor: '#0A0A0A',
      backgroundTransparent: false,
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean, understated simplicity',
    params: {
      ...DEFAULT_PARAMS,
      weight: 20,
      color1: '#1A1A1A',
      fillMode: 'Solid',
      strokeWidth: 0,
      cornerRadius: 0,
      shadowBlur: 0,
    },
  },
  {
    id: 'gradient-pop',
    name: 'Gradient Pop',
    description: 'Bold gradients with rounded shapes',
    params: {
      ...DEFAULT_PARAMS,
      color1: '#FF6B6B',
      color2: '#4ECDC4',
      fillMode: 'Linear Gradient',
      gradientAngle: 135,
      cornerRadius: 20,
      frameShape: 'Squircle',
      framePadding: 15,
    },
  },
  {
    id: 'shadow-stack',
    name: 'Shadow Stack',
    description: 'Layered depth with echo shadows',
    params: {
      ...DEFAULT_PARAMS,
      echoCount: 3,
      echoOffsetX: 8,
      echoOffsetY: 8,
      echoOpacityFalloff: 60,
      color1: '#2563EB',
      shadowX: 4,
      shadowY: 4,
      shadowBlur: 0,
      shadowColor: '#000000',
    },
  },
  {
    id: 'glass',
    name: 'Glass',
    description: 'Frosted glass morphism effect',
    params: {
      ...DEFAULT_PARAMS,
      color1: '#FFFFFF',
      fillMode: 'Solid',
      strokeColor: '#FFFFFF',
      strokeWidth: 1,
      glowIntensity: 10,
      backgroundColor: '#6366F1',
      backgroundTransparent: false,
    },
  },
];
