export type ParamType = 'slider' | 'dropdown' | 'color' | 'toggle';
export type SectionId = 'geometry' | 'curvature' | 'composition' | 'color' | 'decoration' | 'frame';

export interface ParamConfig {
  id: string;
  label: string;
  type: ParamType;
  section: SectionId;
  // Slider props
  min?: number;
  max?: number;
  default: any;
  step?: number;
  // Dropdown props
  options?: string[];
  // Randomizable
  randomizable: boolean;
  randomMin?: number;
  randomMax?: number;
}

export const PARAMS: ParamConfig[] = [
  // ─── Geometry ──────────────────────────────────────────────────────────────
  {
    id: 'weight',
    label: 'Weight',
    type: 'slider',
    section: 'geometry',
    min: 1,
    max: 200,
    default: 40,
    step: 1,
    randomizable: true,
    randomMin: 20,
    randomMax: 180,
  },
  {
    id: 'scaleX',
    label: 'Width %',
    type: 'slider',
    section: 'geometry',
    min: 50,
    max: 200,
    default: 100,
    step: 1,
    randomizable: true,
    randomMin: 70,
    randomMax: 140,
  },
  {
    id: 'scaleY',
    label: 'Height %',
    type: 'slider',
    section: 'geometry',
    min: 50,
    max: 200,
    default: 100,
    step: 1,
    randomizable: true,
    randomMin: 70,
    randomMax: 140,
  },
  {
    id: 'slant',
    label: 'Slant',
    type: 'slider',
    section: 'geometry',
    min: -45,
    max: 45,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -25,
    randomMax: 25,
  },
  {
    id: 'rotation',
    label: 'Rotation',
    type: 'slider',
    section: 'geometry',
    min: -180,
    max: 180,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -15,
    randomMax: 15,
  },
  {
    id: 'cornerRadius',
    label: 'Corner Radius',
    type: 'slider',
    section: 'geometry',
    min: 0,
    max: 100,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 40,
  },
  {
    id: 'terminalStyle',
    label: 'Terminal Style',
    type: 'dropdown',
    section: 'geometry',
    default: 'Round',
    options: ['Butt', 'Round', 'Square', 'Pointed', 'Flared'],
    randomizable: false,
  },
  {
    id: 'jointStyle',
    label: 'Joint Style',
    type: 'dropdown',
    section: 'geometry',
    default: 'Round',
    options: ['Miter', 'Round', 'Bevel'],
    randomizable: false,
  },

  // ─── Curvature ─────────────────────────────────────────────────────────────
  {
    id: 'curveSmoothing',
    label: 'Curve Smoothing',
    type: 'slider',
    section: 'curvature',
    min: 0,
    max: 100,
    default: 50,
    step: 1,
    randomizable: true,
    randomMin: 20,
    randomMax: 90,
  },
  {
    id: 'waveAmplitude',
    label: 'Wave Amplitude',
    type: 'slider',
    section: 'curvature',
    min: 0,
    max: 50,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 20,
  },
  {
    id: 'waveFrequency',
    label: 'Wave Frequency',
    type: 'slider',
    section: 'curvature',
    min: 0,
    max: 20,
    default: 4,
    step: 1,
    randomizable: true,
    randomMin: 1,
    randomMax: 12,
  },
  {
    id: 'noiseAmount',
    label: 'Noise Amount',
    type: 'slider',
    section: 'curvature',
    min: 0,
    max: 30,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 10,
  },
  {
    id: 'noiseSeed',
    label: 'Noise Seed',
    type: 'slider',
    section: 'curvature',
    min: 0,
    max: 9999,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 9999,
  },
  {
    id: 'twist',
    label: 'Twist',
    type: 'slider',
    section: 'curvature',
    min: -360,
    max: 360,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -90,
    randomMax: 90,
  },
  {
    id: 'bulge',
    label: 'Bulge',
    type: 'slider',
    section: 'curvature',
    min: -100,
    max: 100,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -40,
    randomMax: 40,
  },

  // ─── Composition ───────────────────────────────────────────────────────────
  {
    id: 'mirror',
    label: 'Mirror',
    type: 'dropdown',
    section: 'composition',
    default: 'Off',
    options: ['Off', 'Horizontal', 'Vertical', 'Both'],
    randomizable: false,
  },
  {
    id: 'rotationalSymmetry',
    label: 'Rotational Symmetry',
    type: 'slider',
    section: 'composition',
    min: 1,
    max: 12,
    default: 1,
    step: 1,
    randomizable: true,
    randomMin: 1,
    randomMax: 6,
  },
  {
    id: 'echoCount',
    label: 'Echo Count',
    type: 'slider',
    section: 'composition',
    min: 1,
    max: 10,
    default: 1,
    step: 1,
    randomizable: true,
    randomMin: 1,
    randomMax: 5,
  },
  {
    id: 'echoOffsetX',
    label: 'Echo Offset X',
    type: 'slider',
    section: 'composition',
    min: -100,
    max: 100,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -40,
    randomMax: 40,
  },
  {
    id: 'echoOffsetY',
    label: 'Echo Offset Y',
    type: 'slider',
    section: 'composition',
    min: -100,
    max: 100,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -40,
    randomMax: 40,
  },
  {
    id: 'echoOpacityFalloff',
    label: 'Echo Opacity Falloff',
    type: 'slider',
    section: 'composition',
    min: 0,
    max: 100,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 20,
    randomMax: 80,
  },

  // ─── Color ─────────────────────────────────────────────────────────────────
  {
    id: 'fillMode',
    label: 'Fill Mode',
    type: 'dropdown',
    section: 'color',
    default: 'Solid',
    options: ['Solid', 'Linear Gradient', 'Radial Gradient', 'Conic', 'None'],
    randomizable: false,
  },
  {
    id: 'color1',
    label: 'Color 1',
    type: 'color',
    section: 'color',
    default: '#3B82F6',
    randomizable: false,
  },
  {
    id: 'color2',
    label: 'Color 2',
    type: 'color',
    section: 'color',
    default: '#8B5CF6',
    randomizable: false,
  },
  {
    id: 'gradientAngle',
    label: 'Gradient Angle',
    type: 'slider',
    section: 'color',
    min: 0,
    max: 360,
    default: 45,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 360,
  },
  {
    id: 'strokeColor',
    label: 'Stroke Color',
    type: 'color',
    section: 'color',
    default: '#1E3A5F',
    randomizable: false,
  },
  {
    id: 'strokeWidth',
    label: 'Stroke Width',
    type: 'slider',
    section: 'color',
    min: 0,
    max: 20,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 8,
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    section: 'color',
    default: '#FFFFFF',
    randomizable: false,
  },
  {
    id: 'backgroundTransparent',
    label: 'Transparent BG',
    type: 'toggle',
    section: 'color',
    default: false,
    randomizable: false,
  },
  {
    id: 'blendMode',
    label: 'Blend Mode',
    type: 'dropdown',
    section: 'color',
    default: 'Normal',
    options: ['Normal', 'Multiply', 'Screen', 'Overlay', 'Difference'],
    randomizable: false,
  },

  // ─── Decoration ────────────────────────────────────────────────────────────
  {
    id: 'inlineOffset',
    label: 'Inline Offset',
    type: 'slider',
    section: 'decoration',
    min: 0,
    max: 30,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 15,
  },
  {
    id: 'shadowX',
    label: 'Shadow X',
    type: 'slider',
    section: 'decoration',
    min: -30,
    max: 30,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -10,
    randomMax: 10,
  },
  {
    id: 'shadowY',
    label: 'Shadow Y',
    type: 'slider',
    section: 'decoration',
    min: -30,
    max: 30,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: -10,
    randomMax: 10,
  },
  {
    id: 'shadowBlur',
    label: 'Shadow Blur',
    type: 'slider',
    section: 'decoration',
    min: 0,
    max: 50,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 20,
  },
  {
    id: 'shadowColor',
    label: 'Shadow Color',
    type: 'color',
    section: 'decoration',
    default: '#00000066',
    randomizable: false,
  },
  {
    id: 'glowIntensity',
    label: 'Glow Intensity',
    type: 'slider',
    section: 'decoration',
    min: 0,
    max: 50,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 30,
  },
  {
    id: 'grainAmount',
    label: 'Grain Amount',
    type: 'slider',
    section: 'decoration',
    min: 0,
    max: 100,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 40,
  },

  // ─── Frame ─────────────────────────────────────────────────────────────────
  {
    id: 'frameShape',
    label: 'Frame Shape',
    type: 'dropdown',
    section: 'frame',
    default: 'None',
    options: ['None', 'Circle', 'Square', 'Squircle', 'Hexagon', 'Shield'],
    randomizable: false,
  },
  {
    id: 'framePadding',
    label: 'Frame Padding',
    type: 'slider',
    section: 'frame',
    min: 0,
    max: 50,
    default: 15,
    step: 1,
    randomizable: true,
    randomMin: 5,
    randomMax: 30,
  },
  {
    id: 'frameStrokeWidth',
    label: 'Frame Stroke Width',
    type: 'slider',
    section: 'frame',
    min: 0,
    max: 20,
    default: 0,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 8,
  },
  {
    id: 'frameStrokeColor',
    label: 'Frame Stroke Color',
    type: 'color',
    section: 'frame',
    default: '#3B82F6',
    randomizable: false,
  },
  {
    id: 'frameFillColor',
    label: 'Frame Fill Color',
    type: 'color',
    section: 'frame',
    default: '#F0F4FF',
    randomizable: false,
  },
  {
    id: 'frameCornerRadius',
    label: 'Frame Corner Radius',
    type: 'slider',
    section: 'frame',
    min: 0,
    max: 50,
    default: 8,
    step: 1,
    randomizable: true,
    randomMin: 0,
    randomMax: 30,
  },
];

export const SECTIONS: { id: SectionId; label: string }[] = [
  { id: 'geometry', label: 'Geometry' },
  { id: 'curvature', label: 'Curvature' },
  { id: 'composition', label: 'Composition' },
  { id: 'color', label: 'Color' },
  { id: 'decoration', label: 'Decoration' },
  { id: 'frame', label: 'Frame' },
];

export const PARAM_MAP: Record<string, ParamConfig> = Object.fromEntries(
  PARAMS.map((p) => [p.id, p])
);

export const DEFAULT_PARAMS: Record<string, any> = Object.fromEntries(
  PARAMS.map((p) => [p.id, p.default])
);

export const FONTS = [
  'Inter',
  'Space Grotesk',
  'DM Serif Display',
  'IBM Plex Mono',
  'Playfair Display',
  'Bebas Neue',
];

// Returns params with defaults substituted for any disabled section.
// Disabled sections have no visual effect; their stored values are preserved.
export function getEffectiveParams(
  params: Record<string, any>,
  disabledSections: Set<string>
): Record<string, any> {
  if (disabledSections.size === 0) return params;
  const result = { ...params };
  for (const p of PARAMS) {
    if (disabledSections.has(p.section)) {
      result[p.id] = p.default;
    }
  }
  return result;
}
